config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/search', to: 'search#index', as: 'search'
  get '/videos/:id', to: 'videos#show', as: 'videos'
  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transcript.rb
class Transcript < ApplicationRecord
    belongs_to :video
end

app/models/video.rb
class Video < ApplicationRecord
    has_one :transcript
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
      @videos = Video.all
    end
  end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def show
        @video = Video.find(params[:id])
        @transcript = "Temporary placeholder so as not to download from youtube just yet." #fetch_transcript(@video.url)
    end

    private

    def fetch_transcript(video_url)
        yt_dlp_path = Rails.root.join('bin','yt-dlp_linux')
        #result = %x{#{yt_dlp_path} --skip-download --write-auto-sub --sub-lang en -o - "#{video_url}"}

        #./yt-dlp_linux --skip-download --write-subs --write-auto-subs --sub-lang en --sub-format ttml --convert-subs srt --output "transcript.%(ext)s" REPLACEHEREWITH && sed -i '' -e '/^[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9] --> [0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]$/d' -e '/^[[:digit:]]\{1,3\}$/d' -e 's/<[^>]*>//g' ./transcript.en.srt && sed -e 's/<[^>]*>//g' -e '/^[[:space:]]*$/d' transcript.en.srt > output.txt && rm transcript.en.srt
        #puts result
        #return result

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
<h2 class="center-align">YouTube Transcript Search</h2>

<%= form_with(url: search_path, method: 'get', remote: true, id: "searchForm") do |form| %>
  <div class="row">
    <div class="input-field col s12">
      <%= form.text_field :query, id: "searchInput", class: "validate", placeholder: "Enter your query" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.submit "Search", class: "btn waves-effect waves-light", id: "searchButton" %>
              
    </div>
  </div>
<% end %>

<div id="searchResults"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeIndexer</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div id="searchResults">
  <h1>All Videos</h1>

  <ul>
    <% @videos.each do |video| %>
      <li>
        <strong><%= video.title %></strong>
        <p>Channel: <%= video.channel %></p>
        <p>URL: <%= link_to video.url, video.url, target: "_blank" %></p>
        <p>URL: <%= link_to 'View Details', videos_path(video) %></p>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Return to Home", root_path, class: "btn" %>

app/views/videos/show.html.erb
<strong><%= @video.title %></strong>
<p>Channel: <%= @video.channel %></p>
<p>URL: <%= link_to @video.url, @video.url, target: "_blank" %></p>
<p>Transcript: <%= @transcript %> </p>